#!/bin/bash

picom -b &
sxhkd &
dunst &
~/.config/polybar/launch.sh &

# set the wallpaper
~/.scripts/update-wallpaper

# use the normal cursor when not hovering over a window
xsetroot -cursor_name left_ptr

bspc monitor eDP-1 -d I II III

bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a \*:origin.exe state=floating
bspc rule -a floating state=floating
