#!/bin/bash

picom -b --experimental-backends &
sxhkd &
dunst &
emacs --daemon &
~/.config/polybar/launch.sh &

[ ! -f ~/.mpd/pid ] && mpd &

# set the wallpaper
~/.scripts/update-wallpaper

# use the normal cursor when not hovering over a window
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc rule -a Emacs state=tiled
