#!/bin/bash

if [ "$#" -eq 0 ];
then
    [ ! -f ~/.scripts/wallpaper ] && exit

    # If there are no args, use the current wallpaper.
    wallpaper=$(< ~/.scripts/wallpaper)
else
    # Use the wallpaper specified and update the current one.
    wallpaper=$(realpath "$1")
    echo "$wallpaper" > ~/.scripts/wallpaper
fi

feh --bg-fill "$wallpaper"
