#!/bin/bash

# crontab entry to check the battery every five minutes:
# */5 * * * * ~/.scripts/low-battery-notify

BAT=/sys/class/power_supply/BAT1
TMPFILE=/tmp/low-battery-warning-sent

state="$(<$BAT/status)"
charge_now=$(<$BAT/charge_now)
charge_full=$(<$BAT/charge_full)
charge_percentage=$(($charge_now * 100 / $charge_full))

if [ -f $TMPFILE ]; then
    [ $state = "Charging" ] && rm $TMPFILE
elif [ "$state" = "Discharging" -a $charge_percentage -le 15 ]; then
    export XAUTHORITY=/home/universe/.Xauthority
    export DISPLAY=:0
    export $(dbus-launch)

    notify-send --urgency=critical "Low battery" "$charge_percentage% battery remaining"
    touch $TMPFILE
fi
