#!/bin/bash

option=$(echo -e "Shutdown\nReboot\nSleep\nLogout" | rofi -dmenu -i)

case "$option" in
    "Shutdown")
        shutdown now
        ;;
    "Reboot")
        reboot
        ;;
    "Sleep")
        systemctl suspend
        ;;
    "Logout")
        bspc quit
        ;;
esac
