#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Usage: $0 <project name> <template name>"
    exit
fi

project_name="$1"
template_name="$2"
template_path="$HOME/.scripts/templates/$template_name"

if [ ! -d "$template_path" ]; then
    echo "No such template."
    exit
fi

if [ -d "$project_name" ]; then
    echo "A directory with that name already exists."
    exit
fi

cp -r "$template_path" "$project_name"

find "$project_name" -type f -exec sed -i "s/%%PROJECT%%/$project_name/g" {} +
